version: "3.7"
services:
    app:
        build:
            args:
                user: ronan
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: library
        container_name: library-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - library

    db:
        image: mysql:8.0
        container_name: library-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: library
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - library

    nginx:
        image: nginx:alpine
        container_name: library-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - library

networks:
    library:
        driver: bridge
